/**
 * Shared IPTC Metadata Types
 *
 * Used by:
 * - Preset IPTC profile (stored as JSONB in participant_presets.iptc_metadata)
 * - XMP parser (reads PhotoMechanic XMP → PresetIptcMetadata)
 * - IPTC finalizer (writes PresetIptcMetadata + participant data → image files)
 * - Preset editor UI (form for editing IPTC profile)
 * - Results page UI (IPTC Pro panel for finalization)
 */

/**
 * Professional IPTC/XMP metadata profile for Getty-ready output.
 * Stored as JSONB in participant_presets.iptc_metadata column.
 *
 * Template fields support placeholders: {name}, {surname}, {number}, {team},
 * {car_model}, {nationality}, {event}, {date}, {persons}
 *
 * Person Shown formats:
 * - 'simple':   "Lando Norris" (name only)
 * - 'extended': "(1) Lando Norris (GBR) - McLaren Mastercard F1 Team - McLaren MCL40 - Mercedes"
 * - 'custom':   uses personShownTemplate with placeholders
 */
export interface PresetIptcMetadata {
  // === CREDITS ===
  credit?: string;              // IPTC:Credit — "Alessio De Marco"
  source?: string;              // IPTC:Source — Agency/source
  copyright?: string;           // IPTC:CopyrightNotice — "© 2025 Alessio De Marco"
  copyrightOwner?: string;      // XMP-plus:CopyrightOwnerName
  copyrightMarked?: boolean;    // XMP-xmpRights:Marked (true/false)
  copyrightUrl?: string;        // XMP-xmpRights:WebStatement

  // === CREATOR ===
  creator?: string;             // IPTC:By-line — Photographer name
  authorsPosition?: string;     // IPTC:By-lineTitle — "Photographer"
  captionWriter?: string;       // IPTC:Writer-Editor

  // === CREATOR CONTACT INFO ===
  contactAddress?: string;
  contactCity?: string;
  contactRegion?: string;
  contactPostalCode?: string;
  contactCountry?: string;
  contactPhone?: string;
  contactEmail?: string;
  contactWebsite?: string;

  // === EVENT INFO (templates con {name}, {number}, {team}) ===
  headlineTemplate?: string;    // "F1 Grande Premio de Sao Paulo 2025"
  titleTemplate?: string;
  descriptionTemplate?: string; // "{name} during the Formula 1 ..." — CAPTION
  eventTemplate?: string;       // XMP-iptcExt:Event
  category?: string;            // "SPO" (IPTC category code)
  intellectualGenre?: string;   // Iptc4xmpCore:IntellectualGenre
  urgency?: string;             // "1"-"8" (IPTC urgency)
  dateCreated?: string;         // "2025-11-06" (override date)

  // === LOCATION ===
  city?: string;
  country?: string;
  countryCode?: string;         // "BRA"
  location?: string;            // "Autodromo Jose Carlos Pace"
  provinceState?: string;
  worldRegion?: string;         // "America"

  // === RIGHTS & SOURCE ===
  digitalSourceType?: string;   // "http://cv.iptc.org/newscodes/digitalsourcetype/digitalCapture"
  modelReleaseStatus?: string;  // "http://ns.useplus.org/ldf/vocab/MR-NON"
  scene?: string[];             // ["SPO"]

  // === KEYWORDS ===
  baseKeywords?: string[];      // Event keywords (F1, Motorsport, Brasil, ...)
  appendKeywords?: boolean;     // true = merge con AI keywords; false = overwrite
  includeVisualTags?: boolean;  // true = include AI visual tags (location, weather, scene, etc.) in keywords

  // === PERSON SHOWN ===
  personShownFormat?: 'simple' | 'extended' | 'custom';  // Format for PersonInImage field
  personShownTemplate?: string; // Custom template: "{name}" o "({number}) {name} ({nationality}) - {team}"
}

/**
 * Configuration for IPTC batch finalization (post-review)
 */
export interface IptcFinalizationConfig {
  iptcMetadata: PresetIptcMetadata;          // IPTC profile from preset
  results: FinalizedResult[];                 // Corrected results from review page
  keywordsMode: 'append' | 'overwrite';      // Merge or replace keywords
  onProgress?: (current: number, total: number, fileName: string) => void;
  onError?: (fileName: string, error: string) => void;
}

/**
 * A matched participant for IPTC finalization
 */
export interface MatchedParticipantData {
  name?: string;
  number?: string;
  team?: string;
  car_model?: string;
  nationality?: string;
  sponsors?: string[];
  metatag?: string;
}

/**
 * A single result item ready for IPTC finalization
 */
export interface FinalizedResult {
  imagePath: string;                          // Original image path
  isRaw: boolean;                             // For JPEG embed vs XMP sidecar decision
  matchedParticipant?: MatchedParticipantData;  // Primary match (backward compat)
  allMatchedParticipants?: MatchedParticipantData[];  // All matches for multi-match images
  aiKeywords?: string[];                      // Keywords generated by AI during processing
  visualTags?: Record<string, string[]>;      // Visual tags by category (location, weather, scene, etc.)
}

/**
 * Summary of IPTC finalization batch operation
 */
export interface IptcFinalizationSummary {
  totalFiles: number;
  successCount: number;
  errorCount: number;
  skippedCount: number;                       // Files without match (only global data written)
  errors: { fileName: string; error: string }[];
  durationMs: number;
}
