-- Migration: Fix face_descriptor to allow NULL
-- Date: 2025-11-26
-- Description: Allow NULL face_descriptor in sport_category_face_photos
--              Descriptor is generated by desktop app after photo upload

-- Remove NOT NULL constraint from face_descriptor
ALTER TABLE sport_category_face_photos
ALTER COLUMN face_descriptor DROP NOT NULL;

-- Add comment explaining the workflow
COMMENT ON COLUMN sport_category_face_photos.face_descriptor IS '128-dimensional face descriptor. NULL until processed by desktop app.';
